import argparse
import json
import tqdm
from graders.valor.evaluate_people_attribute import is_person_synset
from graders.valor.gpt_model import llm
from graders.valor.scorer.valor_eval_attribute_object import CHAIR, print_metrics, save_evaluation_results


def format_object_attribute(attribute_list):
    formatted_attributes = {}
    for idx, att_object_pair in enumerate(attribute_list):
        attr_str = []
        if att_object_pair['attributes'] and (len(att_object_pair["names"][0].split(' '))>1 or not is_person_synset(att_object_pair["synsets"][0])):
            for att in att_object_pair['attributes']:
                attr_str.append(f"({att}, {att_object_pair['names'][0]})")
            formatted_attributes[f'{idx}'] = ', '.join(attr_str)
    return formatted_attributes


def extract_attribute_object(args):
    path = args.caption_path

    with open(path, "r") as f:
        generated_caps = json.load(f)

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract the ranking from given sentences."
        },
    ]
    content = """
        Given an image with a caption that is generated by a vision language model. 
        Please act as a linguistic master and extract the total number and colors of all objects as mentioned in the captions.
        Your answer should be a dict of this format: {"total_num_of_objects": "(NUM, OBJECT)", "objects": {"ORDER": "(ATTRIBUTE, OBJECT)"}}. Remember OBJECT should be in singular format.

        For clarity, consider these examples:

        ### Example 1:
        - Caption: The image shows a set of five colorful modeling clay sticks neatly aligned side by side against a light-colored, almost white background. From left to right, the sequence of colors is as follows:\n\n1. Pink: A vibrant shade of pink, the stick has a slightly flattened side from being pressed or laid down upon a surface, with the other sides retaining a more rounded shape characteristic of new modeling clay sticks.\n2. Red: Next to the pink, a brilliant red stick is placed. Like the pink, it shows signs of slight use, with minor indentations and a softened shape.\n3. Orange: A bright orange stick follows the red one. It seems to be in a similarly used condition as the others, with a mix of flattened and rounded edges.\n4. Yellow: A pure, sunshine yellow stick, again, showing a little bit of wear.\n5. Green: A vivid green stick represents the fifth color. As with its predecessors, it has a slightly squished appearance indicating it has been handled or used.\nIt mirrors the others in terms of the minor signs of use visible on its surface.\n\nThe sticks are placed closely together, creating a rainbow-like gradient from pink to blue. The light is consistent across the photo, which, along with the plain background, draws attention to the bright colors of the clay sticks. From this angle, we cannot see the length of the sticks, but they appear to have a standard length similar to commonly available modeling clay sticks.
        - Result: {"total_num_of_objects": "(5, "clay sticks"), (1, background)", "objects": {"1": "(pink, clay sticks)", "2": "(red, clay sticks)", "3": "(orange, clay sticks)", "4": "(yellow, clay sticks)", "5": "(green, clay sticks)", "6": "(white, background)"}}

        ### Example 2:
        - Caption: On the top shelf, from left to right:\n- A wooden bowl containing two apples. The apples have a yellowish color with some green and brown areas, suggesting they may be golden apples or a similar variety.\n\nOn the bottom shelf, from left to right:\n- The first object is a brown ceramic cup standing upright.\n- The second object is another brown ceramic cup, positioned upside down on top of the first cup, so they form a closed cylinder together.\n- The third object is a stack of two white ceramic cups with a grey band near the bottom.\n- To the right of these cups, there is a stack of five white ceramic bowls.
        - Result: {"total_num_of_objects": "(2, apples), (4, cups), (6, bowls)", "objects": {"1": "(wooden, bowl)", "2": "(yellowish green, apple)", "3": "(yellowish green, apple)", "4": "(brown, cup)", "5": "(brown, cup)", "6": "(white with grey band, cup)", "6": "(white with grey band, cup)", "7": "(white, bowl)", "7": "(white, bowl)", "8": "(white, bowl)", "9": "(white, bowl)", "10": "(white, bowl)"}}

        With these examples in mind, please help me extract the relations based on the information in the caption. You should only return a JSON file without any explanations.
        Here is the caption:
        [CAPTION]"""

    # outpath = args.output_file_path
    out_list = []
    for sample in tqdm.tqdm(generated_caps[:args.sample_num]):
        image_id = sample["image_id"]
        conversation = sample["conversations"]
        if "scene_graph" in sample:
            attributes = format_object_attribute(sample['scene_graph']['objects'])
        elif 'sg' in sample:
            attributes = format_object_attribute(sample['sg']['objects'].values())
        else:
            attributes = format_object_attribute(sample["attributes"])
        for turn in conversation:
            cap_to_gpt = turn['response']
            input = content.replace("[CAPTION]", cap_to_gpt)
            prompt = messages + [{"role": "user", "content": input}]
            llm_output = llm(prompt, args.model)
            current_output = {
                "image_id": image_id,
                "response": llm_output,
                "generated_caption": cap_to_gpt,
                "gt_attributes": attributes,
                "conversations": conversation
            }
            out_list.append(current_output)

        # with open(outpath, "a") as f:
        #     f.write(json.dumps(current_output ) +"\n")
    return out_list


def match_attribute_object(args, generated_cap_info):
    prompt_template = """
        Task: Match the correct (attribute, object) with the same meaning from a ground truth dictionary and a generated dictionary.

        Inputs:
        1. "gt_att_obj":A dictionary with order being the key and the ground-truth (attribute, object) pair being the value. The order is the order of the object in the image.
        Sometimes one object can be, for example "(black, bag), (white, bag), (striped, bag)", it means either "black" or "white" or "striped" is correct for an attribute related with the "bag" and should be matched. 
        2. "generated_att_obj": A dictionary with order being the key and the generated (attribute, object) pair being the value. The order is the order of the object in the generated caption.

        Instructions:
        1. Matching Criteria:
        - For each (attribute, object) in "generated_att_obj", find the (attribute, object) in the "gt_att_obj" that have the same meaning and add it to the "matched_att_obj" dictionary.
        - By the same meaning, we mean the words can be synonyms, can be plural/singular forms of each other and can also have different length of words to express the same meaning of attributes or objects, etc. 
        - If you find that the "generated_att_obj" can be matched with the "gt_att_obj" but the attribute or object in "generated_att_obj" is a broader concept of the attribute or object in "gt_att_obj", for example, one object in "generated_att_obj" is "person", but the "gt_att_obj" don't have "person" but specifically have "man", which is a subcategory of "person", add it to the "broader_concept" dictionary instead of the "matched_att_obj".
        2. Output:
        - A "broader_concept" dictionary: {"ORDER2": {"(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)"}} only if an (ATTRIBUTE1, OBJECT1) with ORDER1 from "generated_att_obj" denotes a broader category of an (ATTRIBUTE2, OBJECT2) with ORDER2 in "gt_att_obj". Notify that Key must be the (ATTRIBUTE1, OBJECT1)from "generated_att_obj", Value must be (ATTRIBUTE2, OBJECT2) from "gt_att_obj". If none, it should be an empty dictionary. ORDER1 should be the same as ORDER2.
        - A "matched_att_obj" dictionary: {"ORDER2": {"(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)"}} only if an (ATTRIBUTE1, OBJECT1) with ORDER1 from "generated_att_obj" can be mapped to an (ATTRIBUTE2, OBJECT2) with ORDER2 in "gt_att_obj" with the matching criteria. Key must be (ATTRIBUTE1, OBJECT1) from "generated_att_obj", Value must be (ATTRIBUTE2, OBJECT2) from "gt_att_obj". It should not contain any (ATTRIBUTE1, OBJECT1) or (ATTRIBUTE2, OBJECT2) from the "broader_concept" dictionary. ORDER1 should be the same as ORDER2.
        - The keys in "broader_concept" and "matched_att_obj" must be the same as "gt_att_obj".
        - In "broader_concept" and "matched_att_obj", you can not map two different (ATTRIBUTE1, OBJECT1) from "generated_att_obj" to the same (ATTRIBUTE2, OBJECT2) from "gt_att_obj" twice.

        For clarity, consider these examples:

        ### BAD Example 1:
        - gt_att_obj: {"1": "(green, lollipop), (yellow, lollipop), (white, stick)", "2": "(orange, candy)", "3": "(green, candy), (yellow, candy), (white, stick)", "4": "(orange, lollipop)", "5": "(blue, lollipop)", "6": "(pink, background)"}
        - generated_att_obj: {"1": "(green, candy)", "2": "(orange, lollipop)", "3": "(yellow, lollipop)", "4": "(light green, candy)", "5": "(pastel pink, background)"}}
        - broader_concept: {"1": {"(green, candy)": "(green, lollipop)"}, "4": {"(light green, candy)": "(green, lollipop)"} }
        - matched_objects: {"2": {"(orange, lollipop)": "(orange, candy)"}, "3": {"(yellow, candy)": "(yellow, lollipop)", "5": {"(pastel pink, background)": "(pink, background)"}}}}
        This is a BAD example because in "broader_concept", you can not map both (green, candy) and (light green, candy) to (green, lollipop) since there is only one (green, lollipop) in "gt_att_obj". In this case, you don't need to map these green-ish objects in "generated_att_obj".
        You cannot map (pastel pink, background) to (pink, background) because they do not have the same order.

        A good example is 
        - broader_concept: {"1": {"(green, candy)": "(green, lollipop)"}}
        - matched_objects: {"2": {"(orange, lollipop)": "(orange, candy)"}, "3": {"(yellow, candy)": "(yellow, lollipop)"}}}

        ### BAD Example 2:
        - gt_att_obj: {"1": "(green, candy)", "2": "(white, candy)", "3": "(yellow, candy)", "4": "(green, candy)"}
        - generated_att_obj: {"1": "(green, lollipop)", "2": "(white, lollipop)", "3": "(yellow, lollipop)", "4": "(yellow, lollipop)", "5": "(light yellow, lollipop)", "6": "(green, lollipop)", "7": "(dark yellow, lollipop)"}
        - broader_concept: {}
        - matched_objects: {"1": {"(green, lollipop)": "(green, candy)"}, "2": {"(white, lollipop)": "(white, candy)"}, "3": {"(yellow, lollipop)": "(yellow, candy)"}, "4": {"(light yellow, lollipop)": "(yellow, candy)"}, "5": {"(green, lollipop)": "(green, candy)"}}
        This is a BAD example because in "matched_object", you cannot map both (yellow, lollipop) and (light yellow, lollipop) to (yellow, candy) since there is only one (yellow, candy) in "gt_att_obj". In this case, you don't need to map these yellow-ish objects in "generated_att_obj".

        A good example is:
        - matched_objects: {"1": {"(green, lollipop)": "(green, candy)"}, "2": {"(white, lollipop)": "(white, candy)"}, "3": {"(yellow, lollipop)": "(yellow, candy)"}, "4": {"(green, lollipop)": "(green, candy)"}}

        With these examples in mind, please help me extract the broader_concept, and matched_objects from the following two inputs. Please note that your answer should only be in a JSON format with the keys only being the broader_concept, and matched_att_obj.  No explanations/note included.
        ```
        - gt_att_obj: [GT_ATT_OBJ]
        - generated_att_obj: [GENERATED_ATT_OBJ]
        ``` 
    """

    # with open(args.gt_file_path, "r") as f:
    #     gt_cap_info = json.load(f)

    # with open(args.generated_file_path, "r") as f:
    #     generated_cap_info = [json.loads(l) for l in f.readlines()]

    output_file = {}

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract information from given sentences."
        },
    ]

    out_list = {}
    for cap in tqdm.tqdm(generated_cap_info):
        image_id = cap["image_id"]
        gt_obj_atts = cap["gt_attributes"]
        generated_obj_atts = cap["response"]["objects"]

        content = prompt_template.replace("[GT_ATT_OBJ]", str(gt_obj_atts))
        content = content.replace("[GENERATED_ATT_OBJ]", str(generated_obj_atts))

        prompt = messages + [{"role": "user", "content": content}]
        llm_output_dict = llm(prompt, args.model)
        output_file[image_id] = llm_output_dict

        if image_id not in out_list.keys():
            current_output = {
                "image_id": image_id,
                "gt_obj_atts": gt_obj_atts,
                "generated_obj_atts": generated_obj_atts,
                "broader_concept": llm_output_dict["broader_concept"],
                "matched_att_obj": llm_output_dict["matched_att_obj"],
                "conversations": cap["conversations"]
                # "caption": cap["generated_caption"]
            }
            out_list[image_id] = current_output
        else:
            length = len(out_list[image_id]["generated_obj_atts"])
            for k, v in generated_obj_atts.items():
                out_list[image_id]["generated_obj_atts"][length+int(k)-1]=v
            # out_list[image_id]["generated_obj_atts"] = out_list[image_id]["generated_obj_atts"] | generated_obj_atts
            out_list[image_id]["broader_concept"] = out_list[image_id]["broader_concept"] | llm_output_dict["broader_concept"]
            out_list[image_id]["matched_att_obj"] = out_list[image_id]["matched_att_obj"] | llm_output_dict["matched_att_obj"]
            # out_list[image_id]["caption"] += f' {cap["generated_caption"]}'

        # current_output = {
        #     "image_id": image_id,
        #     "gt_obj_atts": gt_obj_atts,
        #     "generated_obj_atts": generated_obj_atts,
        #     "matched_att_obj": llm_output_dict["matched_att_obj"],
        #     "broader_concept": llm_output_dict["broader_concept"]
        # }
        # out_list.append(current_output)

        # with open(args.output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    list_of_dicts = [inner_dict for inner_dict in out_list.values()]
    return list_of_dicts


def postprocess_attribute_object(matched_att_obj_file):
    # with open(matched_att_obj_file_path, "r") as f:
    #     matched_att_obj_file = [json.loads(l) for l in f.readlines()]

    out_list = []
    for matched_att_obj in matched_att_obj_file:
        # Original list of attributes from matched objects
        gt_obj_atts_list = list(matched_att_obj["gt_obj_atts"].values())

        # Splitting each string on "),", then flattening the list and stripping spaces
        gt_obj_atts_list = [item.strip() for atts in gt_obj_atts_list for item in atts.split("),")]

        # Initialize a new list for processed attributes
        new_gt_obj_atts_list = []

        # Iterate over the list and pair the attributes correctly
        for idx, item in enumerate(gt_obj_atts_list):
            # Append a ")" to odd indexed items if missing
            if idx % 2 == 0:  # Even index, potentially a start of a new tuple
                if item[-1] != ")":
                    item += ")"
                new_gt_obj_atts_list.append(item)
            else:  # Odd index, simply append the item
                new_gt_obj_atts_list.append(item)

        # Initialize the new dictionaries
        new_matched_att_obj = {}
        new_broader_concept = {}

        # Update "new_matched_att_obj" by filtering out the relevant mappings
        for index, mapping in matched_att_obj["matched_att_obj"].items():
            matched_gt_att_obj = next(iter(mapping.values()), None)
            if matched_gt_att_obj in new_gt_obj_atts_list:
                new_matched_att_obj[index] = mapping
                new_gt_obj_atts_list.remove(matched_gt_att_obj)

        # Update "new_broader_concept" in a similar way
        for index, mapping in matched_att_obj["broader_concept"].items():
            matched_gt_att_obj = next(iter(mapping.values()), None)
            if matched_gt_att_obj in new_gt_obj_atts_list:
                mapping_str = str(mapping)
                if "unknown" and "unspecified" not in mapping_str and matched_gt_att_obj in new_gt_obj_atts_list:
                    new_broader_concept[index] = mapping
                    new_gt_obj_atts_list.remove(matched_gt_att_obj)

        current_output = {
            "image_id": matched_att_obj["image_id"],
            "gt_obj_atts": matched_att_obj["gt_obj_atts"],
            "generated_obj_atts": matched_att_obj["generated_obj_atts"],
            "matched_att_obj": new_matched_att_obj,
            "broader_concept": new_broader_concept,
            "conversations": matched_att_obj["conversations"]
        }
        out_list.append(current_output)

        # with open(output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    return out_list


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="objects extracting")
    parser.add_argument("-ip", "--caption_path",  default='output/caption/Qwen2.5-VL-3B-Instruct_svg.json', type=str)
    parser.add_argument("-op", "--output_file_path", default="output/caption/valor/Qwen2.5-VL-3B-Instruct_svg_valor_obj_att.json", type=str)
    parser.add_argument("--model", type=str, default='gpt-5')
    parser.add_argument("--sample_num", type=int, default=1)
    args = parser.parse_args()

    object_attribute_list = extract_attribute_object(args)
    match_attribute_list = match_attribute_object(args, object_attribute_list)
    match_attribute_list = postprocess_attribute_object(match_attribute_list)

    evaluator = CHAIR(match_attribute_list)
    cap_dict = evaluator.compute_chair()

    print_metrics(cap_dict)
    save_evaluation_results(args, cap_dict)
