import json
from copy import deepcopy
from gpt_model import llm
import tqdm
import argparse

from graders.valor.scorer.valor_eval_relation_positional import CHAIR, print_metrics, save_evaluation_results


def format_gt(region_list):
    reformat_object = []
    if "objects" in region_list:
        object_list = region_list["objects"]
        for rel in region_list["relations"]:
            reformat_object.append(f'{object_list[rel[0]]} {rel[2].lower()} {object_list[rel[1]]}')
    else:
        for obj in region_list:
            # reformat_object.append(obj["phrase"].strip())
            reformat_object.append(f'{obj["subject"]["names"][0]} {obj["predicate"].lower()} {obj["object"]["names"][0]}')
    return set(reformat_object)


def extract_relation(args):
    path = args.input_file_path

    with open(path, 'r') as f:
        generated_caps = json.load(f)

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract information from given sentences."
        },
    ]
    content = """Given an image with a caption that is generated by a vision language model. 
        Please act as a linguistic master and extract a set of words describing the spatial or positional relations between all the visual objects from the captions.
        Your answer should be a list of values that are in format of object1 relation with object2 with the relation being left, right, top, bottom, middle etc.
        Do not extract the attribute along with the object and don't extract any relation that is an verb, replace it with simply which object is (on or to the left or etc) the other object or the image. Formulate your response into a JSON object with the key being "relations" and the value being a list of relations. 
        If there are no relations found, please return an empty list.
        For clarity, consider these examples:

        ### Example 1:
        - Caption: The relationship between the objects in the image is that the knife is on the right side of the cutting board, the banana is on the left side of the cutting board, and the cheese is underneath the cutting board.
        - relations: [knife is on the right side of the cutting board, the banana is on the left side of the cutting board, the cheese is underneath the cutting board]

        ### Example 2:
        - Caption: The relationship between the objects in the image is that a man is playing with his dog on a sandy beach. The man is standing on the left side of the image, while the dog is running on the right side of the image. The dog is chasing a frisbee thrown by the man, who is trying to catch the frisbee before the dog does
        - relations: ["the man is on the beach, the dog is on the beach, the man is on the left side of the image, the man's dog is on the right side of the image]

        ### Example 3:
        - Caption: From the view of the observer, the objects in the image can be described as follows: 
        1. On the left side of the image, there is a wooden chair with a red cushion. 
        The chair is placed near a window, which allows natural light to enter the room. 
        2. On the right side of the image, there is a small table with a vase of flowers on it. 
        The vase contains pink and purple tulips, adding a touch of color and beauty to the room. 
        3. At the bottom of the image, there is a rug with a floral pattern. 
        The rug complements the vase of flowers on the table and enhances the overall aesthetic of the room.
        - relations: [wooden chair is on the left side of the image,  chair is near a window, a vase of flowers on the table, a small table is on the right side of the image, a vase of flower is on the right side of the image, a rug at the bottom of the image]
        Notice that here in the sentence "On the right side of the image, there is a small table with a vase of flowers on it." We can extract three relations from it: 1. a vase of flowers on the table, 2. a small table is on the right side of the image, 3. a vase of flower is on the right side of the image.

        With these examples in mind, please help me extract the relations based on the information in the caption.
        Here is the caption:
        {}"""

    out_list = []
    # outpath = args.output_file_path
    for sample in tqdm.tqdm(generated_caps[:args.sample_num]):
        image_id = sample["image_id"]
        conversation = sample["conversations"]
        if "scene_graph" in sample:
            gt_words = list(format_gt(sample["scene_graph"]))
        elif "sg" in sample:
            gt_words = list(format_gt(sample["sg"]["relationships"]))
        else:
            gt_words = list(format_gt(sample["relationships"]))

        for turn in conversation:
            input = content.format(turn['response'])
            prompt = messages + [{"role": "user", "content": input}]
            llm_output = llm(prompt, args.model)
            # print("prompt", prompt)
            # print(llm_output)
            current_output = {
                "image_id": image_id,
                "response": llm_output,
                # "generated_caption": turn['response'],
                'gt_words': gt_words,
                "conversations": conversation
            }
            out_list.append(current_output)
            # with open(outpath, "a") as f:
            #     f.write(json.dumps(current_output) + "\n")
            #
            # print(llm_output)
    return out_list


def postprocess(image_id, objects):
    # Unwanted relations
    fake_ralations = ["complements", "complement", "towards", "through",  # 'wearing'
                      "holding", "using", "appears", "penetrating", "reads", "separated", "has"
                      ]

    filtered_objects = []
    for obj in objects:
        # filter action word ending with "ing", might use nltk to improve this?
        # if obj.endswith("ing"):
        #     objects.remove(obj)
        #     next
        words = obj.split()
        for word in words:
            if word in fake_ralations:
                filtered_objects.append(obj)

    # print(image_id, f"Filtered {len(filtered_objects)} objects", filtered_objects)
    returned_objects = [obj for obj in objects if obj not in filtered_objects]

    return returned_objects


def postprocess_relation(captions):
    # with open(args.caption_path, "r") as f:
    #     captions = [json.loads(l) for l in f.readlines()]

    out = deepcopy(captions)
    for idx, item in enumerate(out):
        image_id = item["image_id"]
        objects = item["response"]["relations"]
        objects = postprocess(image_id, objects)
        item["generated_words"] = objects

    # with open(args.input_path, "a") as outfile:
    #     for entry in out:
    #         json.dump(entry, outfile)
    #         outfile.write('\n')
    return out


def match_relation(cap_info):
    prompt_template = """
        Task: Match (object-1 positional relation with object-2) from a ground truth dictionary and a list based on their meaning.

        Inputs:
        1. "gt_relations": A dictionary of ground truth relations. Each key is a number with no meaning of order. Each key represents different relations. The values is a list of one or two relations, 
        if there are two relations, they are synonyms. Sometimes in one relation it contains for example "image / table", it means either image or table in this phrase is correct. 
        2. "generated_relations": A list of generated relations from a model.

        Instructions:
        1. Matching Criteria:
        - For each relation in "generated_relations", find the corresponding relation in "gt_relations" based on their meaning, if there is none, skip it.
        - If you find a match, add it to the "matched_relations" dictionary. Note that if there are two relations in a item of "gt_relations", 
        it means the same meaning of the relation, you can pick either one of them as the match to the relation in "generated_relations".
        - If you find that the generated relation is a broader concept of a relation in "gt_relations" such as the generated relation is near each other, next to, in touch etc. 
        but the gt_relation specifically have their relation is specifically left, right, behind or front, etc, which is more than near, add it to the "broader_concept" dictionary.
        2. Output:
        - A "broader_concept" dictionary: only if an relation from "generated_relations" denotes a broader category of a concept in "gt_relations" Notify that Key must be the item from "generated_relations", Value must be item from "gt_relations". If none, it should be an empty dictionary.
        - A "matched_relations" dictionary: only if an relation from "generated_relations can be mapped to an relation in "gt_relations" with the matching criteria. Key must be word from "generated_relations", Value must be word from "gt_relations". It should not contain any words from the "broader_concept" dictionary.

        For clarity, consider these examples:
        ### Example 1:
        - gt_relations:{"0": ["the television is on the right side of the image"], "1": ["leaves are on the left side of the image"], "2": ["the television is on the ground", "the ground is under the television"], "3": ["leaves are on the ground", "the ground is under the leaves"], "4": ["the television is to the right of the leaves", "the leaves are to the left of the television"]}
        - generated_relations: ["an old television set is on the left side of the image", "a broken television set is on the right side of the image", "a remote control is at the top of the image"]
        - broader_concept: {}
        - matched_relations:{"a broken television set is on the right side of the image": "the television is on the right side of the image"}

        ### Example 2:
        - gt_relations:{"0": ["the teddy bear is on the right side of the image"],"1": ["the teddy bear is on the ground"],"2": ["the teddy bear is to the right of the trash bin", "the trash bin is to the left of the teddy bear"],"3": ["the trash bin is on the ground"],"4": ["the trash bag is on the ground"],"5": ["the trash bin is to the right of the trash bag", "the trash bag is to the left of the trash bin"],"6": ["the trash bin is in the middle of the image"],"7": ["one trash bag is on the left side of the image"],"8": ["one trash bag is on the right side of the image"],"9": ["the teddy bear is to the right of the trash bag", "the trash bag is to the left of the teddy bear"]}
        - generated_relations:["a large teddy bear is on the ground", "a large teddy bear is next to a green trash can", "a green trash can is on the right side of the image", "a large teddy bear is on the left side of the image", "two black trash bags are on the ground", "one black trash bag is on the left side of the image", "one black trash bag is on the right side of the image"]
        - broader_concept: {"a large teddy bear is next to a green trash can": "the teddy bear is to the right of the trash bin"}
        - matched_relations:{"a large teddy bear is on the ground": "the teddy bear is on the ground", "two black trash bags are on the ground": "the trash bag is on the ground", "one black trash bag is on the left side of the image":"the trash bag is on the left side of the image", "one black trash bag is on the right side of the image": "one trash bag is on the right side of the image"}    
        With these examples in mind, please help me extract the broader_concept, and matched_relations from the following two inputs.
        ```
        - gt_relations: [GT_RELATIONS]
        - generated_relations: [GENERATED_RELATIONS]
        ```
        Please note that your answer should only be in a JSON format with the keys only being the broader_concept, and matched_relations.
        No explanations/note included."""

    # with open(args.input_file_path, "r") as f:
    #     cap_info = [json.loads(l) for l in f.readlines()]

    out_list = {}
    for cap in tqdm.tqdm(cap_info):
        image_id = cap["image_id"]
        gt_objects = cap["gt_words"]
        generated_objects = cap["generated_words"]
        # generated_caption = cap["generated_caption"]

        content = prompt_template.replace("[GT_RELATIONS]", str(gt_objects))
        content = content.replace("[GENERATED_RELATIONS]", str(generated_objects))

        prompt = [{"role": "user", "content": content}]
        llm_output_dict = llm(prompt, args.model)
        if image_id not in out_list.keys():
            current_output = {
                "image_id": image_id,
                "gt_words": gt_objects,
                "generated_words": generated_objects,
                "broader_concept": llm_output_dict["broader_concept"],
                "matched_objects": llm_output_dict["matched_relations"],
                # "generated_caption": generated_caption,
                "conversations": cap["conversations"]
            }
            out_list[image_id] = current_output
        else:
            out_list[image_id]["generated_words"] += generated_objects
            out_list[image_id]["broader_concept"] = out_list[image_id]["broader_concept"] | llm_output_dict["broader_concept"]
            out_list[image_id]["matched_objects"] = out_list[image_id]["matched_objects"] | llm_output_dict["matched_relations"]
            # out_list[image_id]["generated_caption"] += f' {generated_caption}'

        # print("matched_objects", llm_output_dict["matched_relations"])
        # with open(args.output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    list_of_dicts = [inner_dict for inner_dict in out_list.values()]
    return list_of_dicts


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="objects extracting")
    parser.add_argument("-ip", "--input_file_path", default='output/caption/Qwen2.5-VL-3B-Instruct.json', type=str)
    parser.add_argument("-op", "--output_file_path", default="output/caption/valor/Qwen2.5-VL-3B-Instruct_pos.json", type=str)
    parser.add_argument("--model", type=str, default='gpt-5')
    parser.add_argument("--sample_num", type=int, default=3)
    args = parser.parse_args()

    relation_list = extract_relation(args)
    postprocess_relation_list = postprocess_relation(relation_list)
    match_relation_list = match_relation(postprocess_relation_list)

    evaluator = CHAIR(match_relation_list)
    cap_dict = evaluator.compute_chair()

    print_metrics(cap_dict)
    save_evaluation_results(args, cap_dict)
