import json
import tqdm
import argparse
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from graders.valor.gpt_model import llm
from graders.valor.scorer.valor_eval_object_existence import CHAIR, print_metrics, save_evaluation_results

lemmatizer = WordNetLemmatizer()


def extract_object(args):
    with open(args.caption_path, "r") as f:
        generated_caps = json.load(f)

    prompt_template = """
        Given an image with a caption that is generated by a vision language model. 
        Please act as a linguistic master and extract all the objects from the captions and format your response in a 
        JSON format with the key being "objects" and the value being a list of objects. 

        Please only extract objects without including attributes. For example, extract "field" instead of "grassy field". 
        Also be mindful of plural forms. For example, extract "cow" instead of "cows".
        Don't extract the role of people, such as spectator, player, audience, mother, etc. 
        Please only extract the object that is a concrete entity in the real world instead of abstract concepts, actions, and moves. 
        It cannot be an abstract notion such as day, time, scene, moment, image, game, sport, setting, plot, atmosphere, surroundings, group etc.
        It cannot be any words describing the emotions such as excitement, enthusiasm, etc. 
        It cannot be any words describing the positions in the image, such as foreground, background, left, right, etc.

        For clarity, consider these examples:

        ### Example 1:
        - Caption: In the image, a young boy is holding an umbrella and petting a cow in a grassy field. 
        There are several other people scattered throughout the scene, some of whom appear to be watching the boy interacting with the cow. 
        Additionally, there are several other cows in the field, some of which are closer to the boy while others are further away. 
        The overall atmosphere is peaceful and relaxed, with the boy and the cows seemingly enjoying each other's company.
        - objects: [boy, umbrella, cow, field, people]

        ### Example 2:
        - Caption: The image depicts a group of young men playing a game of rugby on a lush green field. 
        They are gathered in the middle of the field, with one player standing on top of another's shoulders. 
        There are several other players scattered around the field, creating a lively and energetic atmosphere.  
        In addition to the rugby players, there are several other people visible in the background, possibly spectators or supporters of the game. 
        One person is positioned towards the left side of the image, while another can be seen towards the right side. 
        A third person is located closer to the center of the image. 
        Overall, the scene captures the excitement and enthusiasm of the rugby players as they engage in their sport.
        - objects: [men, field, people, person]

        ### Example 3: 
        - Caption: The image features a woman sitting on a green bench in front of a large church. 
        She is wearing a hat and appears to be enjoying the sunny day. She is also holding a box and enjoying her food.
        There are several other people in the scene, including a man and a child, who are walking around the area. 
        In the background, there is a fountain with water flowing from it, adding to the serene atmosphere of the scene. 
        A clock can be seen hanging on the side of the church, indicating the time of day. 
        Overall, the image captures a peaceful moment in a beautiful outdoor setting, with the green bench providing a comfortable spot for the woman to rest and enjoy the surroundings.
        - objects: [woman, bench, church, hat, box, food, people, man, child, fountain, water, clock]

        With these examples in mind, please help me extract the objects based on the factual information in the caption.
        Here is the caption:
        {}
    """

    # outpath = args.output_file_path
    outfile = {}

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract information from given sentences."
        },
    ]
    output_list = []
    for sample in tqdm.tqdm(generated_caps[:args.sample_num]):
        image_id = sample["image_id"]
        conversation = sample["conversations"]

        for turn in conversation:
            content = prompt_template.format(turn['response'])
            prompt = messages + [{"role": "user", "content": content}]
            llm_output = llm(prompt, args.model)
            # print(llm_output)
            outfile[image_id] = llm_output
            if "sg" in sample.keys():
                current_output = {
                    "image_id": image_id,
                    "gt_objects": sample["sg"]["objects"].values(),
                    "response": llm_output,
                    "caption": turn['response'],
                    "conversations": conversation
                }
            else:
                current_output = {
                    "image_id": image_id,
                    "gt_objects": sample["objects"],
                    "response": llm_output,
                    "caption": turn['response'],
                    "conversations": conversation
                }
            output_list.append(current_output)
            # with open(outpath, "a") as f:
            #     f.write(json.dumps(current_output) + "\n")
    return output_list


def postprocess(image_id, objects):
    # Unwanted objects
    fake_objects = ["atmosphere", "scene", "sport", "sports", "game", "time", "trip", "items",
                    "scenery", "foreground", "background", "group", "backdrop", "meal",
                    "day", "days", "conversation", "protection", "sense of", "product", "appliance",
                    "outdoor", "activity", "activities", "event", "events", "occasion", "occasions",
                    "work", "works", "job", "jobs", "occupation", "occupations", "journey", 'design', 'comfort',
                    'elegance', 'relaxation', 'grooming'
                    ]
    positions = ["left side", "right side", "top left", "top right", "bottom left", "bottom right", "center", "middle",
                 "top", "bottom", "front", "back"]
    # body_parts = ["head", "face", "eyes", "mouth", "nose", "ears", "hair", "neck", "shoulder", "chest", "arm", "elbow", "wrist", "hand", "fingers", "leg", "knee", "ankle", "foot", "toes"]
    numbers = ["one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]
    # space
    space = ["space", "area", "room", "cityscape", "shoreline"]
    color = ["greenery", "blue", "red", "yellow", "orange", "purple", "pink", "white", "black", "grey",
             "brown", "colorful", "color", "colors", "colored", "colours", "coloured", "colour"]
    # also check family, girl, boy this kind of words
    family = ["mother", "father", "brother", "sister", "grandmother", "grandfather", "aunt", "uncle",
              "cousin", "niece", "nephew", "daughter", "son", "wife", "husband"]
    relationships = ["friend", "lover"]
    scene = ["sun", "sunrays", "sunray"]
    roles = ["spectator", "spectators", "player", "audience", "mother", "supporter", "supporters", 'players',
             'spectators', 'sidelines', 'batter', 'batter', 'catcher', 'umpire']
    new_add = ['shapes', 'sizes', 'access', 'image', 'picture', 'options', "side", "sides", "adventure", "parasailing",
               "gesture", 'beauty', 'surroundings'
                                    "moment", 'Ben', 'Westminster', 'Thames', 'context', 'setting', 'moment', "trick",
               'skill', 'enthusiasm', 'place', 'break', "couple", 'gathering',
               "pitch", 'zone', 'facilities', 'coloration', 'pigments', 'diet', 'appearance', 'environment', 'bokeh',
               'portrait', 'photograph', 'format', 'border', 'positioning', 'posture',
               'structure', 'service', 'reflection', 'photography', "arrangements", 'patterns', 'shadows', 'beams',
               'motion', 'concentration', 'solitude',
               "sunlight", 'overpass', 'movement', 'life', 'transportation', 'nature', 'horizon', 'daylight',
               'lighting', 'patterns', 'habitat', 'frame',
               'landscape', 'music', 'facade', 'rides', 'shape', 'climate', 'location', 'neighborhood', 'interior']

    filtered_objects = []
    for obj in objects:
        # filter action word ending with "ing", might use nltk to improve this?
        # if obj.endswith("ing"):
        #     objects.remove(obj)
        #     next
        words = obj.split()
        for word in words:
            if word in fake_objects or word in positions or word in space or word in numbers or word in color \
                    or word in relationships or word in scene or word in roles or word in new_add or word in family:
                filtered_objects.append(obj)

    # print(image_id, f"Filtered {len(filtered_objects)} objects", filtered_objects)
    returned_objects = [lemmatizer.lemmatize(obj, pos=wordnet.NOUN) for obj in objects if obj not in filtered_objects]

    return returned_objects


def postprocess_object(captions):
    # with open(args.caption_path, "r") as f:
    #     captions = [json.loads(l) for l in f.readlines()]
    output_list = []
    for item in captions:
        image_id = item["image_id"]
        objects = item["response"]["objects"]
        objects = postprocess(image_id, objects)
        out = {
            "image_id": image_id,
            "gt_objects": item["gt_objects"],
            "objects": objects,
            "caption": item["caption"],
            "conversations": item["conversations"]
        }
        # with open(args.output_path, "a") as f:
        #     f.write(json.dumps(out) + "\n")
        output_list.append(out)
    return output_list


def prepare_match(extracted_relations):
    # gt_words = args.gt_path
    # with open(gt_words, 'r') as f:
    #     gt_annotate = [json.loads(l) for l in f.readlines()]
    # gt_words = {}
    # for i, item in enumerate(gt_annotate):
    #     gt_words[item['image_id']] = item['gt_objects']

    # extracted_relations = args.extracted_path
    # with open(extracted_relations, 'r') as f:
    #     extracted_relations = [json.loads(l) for l in f.readlines()]
    #
    # outpath = args.output_path
    # if os.path.exists(outpath):
    #     os.remove(outpath)
    output_list = []
    for relation in extracted_relations:
        image_id = relation['image_id']
        gt_words = set([lemmatizer.lemmatize(item["names"][0], pos=wordnet.NOUN) for item in relation['gt_objects']])
        generated = relation['objects']
        out = {
            'image_id': image_id,
            'gt_words': list(gt_words),
            'generated_words': generated,
            "generated_caption": relation['caption'],
            "conversations": relation["conversations"]
        }
        # with open(outpath, "a") as f:
        #     f.write(json.dumps(out) + "\n")
        output_list.append(out)
    return output_list


def match_object(args, cap_info):
    prompt_template = """
        Task: Match objects from two lists based on their meaning.

        Input Lists:
        1. "gt_objects": A list of objects in the image.
        2. "generated_objects": A list of objects identified by a vision language model.

        For each object in "generated_objects", find the object in the "gt_objects" that have the same meaning and add it to the "matched_objects" dictionary.
        By the same meaning, we mean the words can be synonyms, can be plural/singular forms of each other and can also have different length of words to express the same meaning of objects, etc.
        Note since we find the matched object for each object in "generated_objects", it's ok that multiple objects in "generated_objects" match one object in "gt_objects", list all matches.
        There is special scenario that when you can't find the matched object in "gt_objects" but you can find one or more object is a subset or a sub category of the generated object, which means that the generated object is a broader concept of the object in "gt_objects", add it to the "broader_concept" dictionary instead of the "matched_objects". If there are many objects are a subset or a sub category of the generated object, you can pick anyone of them. Note we are matching for each object in "generated_objects". If you can find the matched object in "gt_objects", you should not add it to the "broader_concept" dictionary.
        Note that broader concept doesn't mean more of the same object, it means a broader category of the object. For example, "plant" is a broader concept of "flower" and "food" is a broader concept of "broccoli". However, since 'people' is plural of 'person', 'people' is not a broader concept of 'person'.

        Output:
        - A "broader_concept" dictionary: only if an object from "generated_objects" denotes a broader category of a concept in "gt_objects", not vice versa, like "plant" is a broader conecpt of "flower" and "food" is a broader concept of "broccoli". Key = word from "generated_objects", Value = word from "gt_objects".
        - A "matched_objects" dictionary: only if an object from "generated_objects can be mapped to an object in "gt_objects" with the matching criteria. Key = word from "generated_objects", Value = word from "gt_objects". It should not contain any words from the "broader_concept" dictionary.

        For clarity, consider these examples:
        ### Example 1:
        - gt_objects: ["bench", "fence", "bell", "clock", "doorway", "hat", "shoe", "steps", "building", "roof", "people", "woman", "pigeon", "tree", "sky", "clouds", "dress"]
        - generated_objects: ["woman", "bench", "church", "hat", "people", "man", "child", "fountain", "water", "clock"]
        - broader_concept: {}
        - matched_objects:{"woman": "woman", "bench": "bench", "hat": "hat", "people": "people", "clock": "clock"}
        ### Example 2:
        - gt_objects: ["sock", "person", "trees", "players", "outfit", "ball", "guys", "uniform", "man", "guy", "field", "frisbee","street","sign","people", "shoe", "tree", "player", "arm"]
        - generated_objects: ["men", "field", "player", "people", "spectators", "supporters", "person", "road", "street signs"]
        - broader_concept: {}
        - matched_objects: {"men": "man, "field": "field", "player": "player", "people": "people", "person": "person", 'road': 'street' 'street signs': 'sign'}
        ### Example 3:
        - gt_words: ["vase", "flowers", "wall", "staircase", "doors", "lamps", "pillows", "bedroom", "comforter", "lamp", "bed", "flowers", "sheets", "headboard", "wall", "ceiling", "nightstand"] 
        - generated_words: ["bedroom", "bed", "pillows", "lamps", "plants", "potted plants", "vase", "nightstand"] 
        - broader_concept: {"plants": "flowers", "potted plants": "flowers"} 
        - matched_objects: {"bedroom": "bedroom", "bed": "bed", "pillows": "pillows", "lamps": "lamps", "vase": "vase", "nightstand": "nightstand"}
        ### Example 4:
        - gt_words: ["hand", "game controller", "pants", "man", "arm", "earring", "woman", "can", "table", "hair", "woman", "shirt", "coffee table", "glasses", "water", "candle", "pole", "t-shirt", "shorts", "sofa"] 
        - generated_words: ["people", "couch", "men", "woman", "Wii remote", "screen", "cups", "coffee table", "bottle", "potted plant"]
        - broader_concept: {"people": "man", "people": "woman"}
        - matched_objects: {"men": "man", "coffee table": "coffee table", "woman": "woman", "Wii remote": "game controller"}
        ### Example 5:
        - gt_words: ['curtains', 'toy', 'wall', 'pajamas', 'water bottle', 'boy', 'lid', 'bed', 'headboard', 'woman', 'mother', 'shirt', 'desk']
        - generated_words: ['child', 'bed', 'pajamas', 't-shirt', 'toys', 'teddy bear', 'doll', 'stuffed animal', 'chair', 'table']
        - broader_concept: {'child': 'boy'}
        - matched_objects: {'mother': 'mother', 'bed': 'bed', 'pajamas': 'pajamas', 't-shirt': 'shirt', 'table': 'desk'}
        ### Example 6:
        - gt_words: ['ground', 'train tracks', 'smoke', 'bridge', 'moss', 'train', 'steam', 'coat', 'tree']
        - generated_words: ['train', 'stone arch bridge', 'dirt road', 'people', 'jacket', 'person', 'cars', 'tree', 'trees']
        - broader_concept: {}
        - matched_objects: {'train': 'train', 'stone arch bridge': 'bridge', 'jacket':'coat', 'tree': 'tree', 'trees': 'tree'}}
        ### Example 7:
        - gt_words: ['blender','countertop', 'microwave', 'cabinets', 'dishwasher', 'sink', 'toaster', 'counter', 'water bottle', 'window', 'sign', 'door', 'bar stool', 'bar stool', 'kitchen', 'refrigerator']
        - generated_words: ['kitchen', 'cabinets', 'countertops', 'refrigerator', 'microwave oven', 'dishwasher', 'bottles', 'counter', 'wine glass', 'chairs']
        - broader_concept: {'chairs': 'bar stool', 'bottles': 'water bottle'}
        - matched_objects: {'kitchen': 'kitchen', 'cabinets': 'cabinets', 'counter': 'counter', 'refrigerator': 'refrigerator', 'microwave oven': 'microwave', 'dishwasher': 'dishwasher', 'countertops': 'countertop'}

        With these examples in mind, please help me extract the broader_concept, and matched_objects from the following two objects lists.
        ```
        - gt_objects: [GT_OBJECTS]
        - generated_objects: [GENERATED_OBJECTS]
        ```
        Please note that your answer should only be in a JSON format with the keys only being the broader_concept, and matched_objects.
        No explanations/note included.
    """

    # with open(args.input_file_path, "r") as f:
    #     cap_info = [json.loads(l) for l in f.readlines()]

    # if args.random:
    #     cap_info = random.sample(cap_info, args.num_random_samples)

    # output_file = {}
    out_list = {}
    for cap in tqdm.tqdm(cap_info):
        image_id = cap["image_id"]
        gt_objects = cap["gt_words"]

        generated_objects = cap["generated_words"]
        generated_objects = list(generated_objects)

        content = prompt_template.replace("[GT_OBJECTS]", str(gt_objects))
        content = content.replace("[GENERATED_OBJECTS]", str(generated_objects))

        prompt = [{"role": "user", "content": content}]
        llm_output_dict = llm(prompt, args.model)

        # output_file[image_id] = llm_output_dict
        if image_id not in out_list.keys():
            current_output = {
                "image_id": image_id,
                "gt_words": gt_objects,
                "generated_words": generated_objects,
                "broader_concept": llm_output_dict["broader_concept"],
                "matched_objects": llm_output_dict["matched_objects"],
                "conversations": cap["conversations"]
                # "caption": cap["generated_caption"]
            }
            out_list[image_id] = current_output
        else:
            out_list[image_id]["generated_words"] += generated_objects
            out_list[image_id]["broader_concept"] = out_list[image_id]["broader_concept"] | llm_output_dict["broader_concept"]
            out_list[image_id]["matched_objects"] = out_list[image_id]["matched_objects"] | llm_output_dict["matched_objects"]
            # out_list[image_id]["caption"] += f' {cap["generated_caption"]}'

        # current_output = {
        #     "image_id": image_id,
        #     "gt_words": gt_objects,
        #     "generated_words": generated_objects,
        #     "broader_concept": llm_output_dict["broader_concept"],
        #     "matched_objects": llm_output_dict["matched_objects"],
        #     "caption": cap["generated_caption"],
        # }
        # print(current_output)
        # out_list.append(current_output)
        # with open(args.output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    list_of_dicts = [inner_dict for inner_dict in out_list.values()]
    return list_of_dicts


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="objects extracting")
    parser.add_argument("-ip", "--caption_path",  default='output/caption/Qwen2.5-VL-3B-Instruct_svg.json', type=str)
    parser.add_argument("-op", "--output_file_path", default="output/caption/valor/Qwen2.5-VL-3B-Instruct_svg_valor_obj_exist.json", type=str)
    parser.add_argument("--model", type=str, default='gpt-5')
    parser.add_argument("--sample_num", type=int, default=3)
    args = parser.parse_args()

    object_list = extract_object(args)
    processed_object_list = postprocess_object(object_list)
    processed_object_list = prepare_match(processed_object_list)
    matched_object = match_object(args, processed_object_list)

    evaluator = CHAIR(matched_object)
    cap_dict = evaluator.compute_chair()

    print_metrics(cap_dict)
    save_evaluation_results(args, cap_dict)
