import argparse
import json
import tqdm
from graders.valor.gpt_model import llm
from nltk.corpus import wordnet as wn

from graders.valor.scorer.valor_eval_attribute_people import CHAIR, print_metrics, save_evaluation_results
from utils.construct_tree import get_hypernym_tree


def is_person_synset(syn):
    syn = wn.synset(syn)
    hypernym_tree = get_hypernym_tree(syn)
    if any(hypernym.name().startswith(("people.n.", "person.n.")) for hypernym in hypernym_tree):
        # print(True, syn, hypernym_tree)
        return True
    # print(False, syn, hypernym_tree)
    return False


def format_people_attribute(image_data):
    final_output = {}
    person_counter = 1
    if isinstance(image_data, dict):
        img_objects = image_data.get('objects').values()
        img_attributes = image_data.get('objects').values()
    else:
        img_objects = image_data.get('objects', [])
        img_attributes = image_data.get('attributes', [])
    img_relationships = image_data.get('relationships', [])

    object_map = {obj['object_id']: obj for obj in img_objects}
    attribute_map = {attr['object_id']: attr for attr in img_attributes}

    # Identify all person objects in the scene
    person_objects = {}
    for obj in img_objects:
        object_synsets = obj.get('synsets', [])
        if len(object_synsets) and is_person_synset(object_synsets[0]):
            person_role = obj['names'][0].lower() if obj['names'] else "person"
            person_objects[obj['object_id']] = person_role

    # Extract features for each identified person
    for person_id, person_role in person_objects.items():
        extracted_objects = set()
        extracted_actions = set()

        # Extract Actions
        person_attr_data = attribute_map.get(person_id, {}).get('attributes')
        if person_attr_data:
            for attr in person_attr_data or []:
                if attr and (attr.endswith('ing') or attr.endswith('ed')):
                    extracted_actions.add(attr.strip().lower())

        for rel in img_relationships:
            subject_id = rel['subject']['object_id']
            object_id = rel['object']['object_id']
            predicate = rel['predicate'].strip().lower()

            if subject_id == person_id:
                if predicate.endswith('ing') or predicate.endswith('ed'):
                    extracted_actions.add(predicate)
                    related_obj_id = object_id
                else:
                    continue
            elif object_id == person_id:
                if predicate.endswith('ing') or predicate.endswith('ed'):
                    extracted_actions.add(predicate)
                    related_obj_id = subject_id
                else:
                    continue
            else:
                continue

            # Extract attributes of the related object/subject
            related_obj = object_map.get(related_obj_id)
            if related_obj:
                obj_name = related_obj['names'][0].lower() if related_obj['names'] else 'item'
                related_attr_data = attribute_map.get(related_obj_id, {})

                attrs = related_attr_data.get('attributes') or []
                attrs = [a.lower() for a in attrs if a and len(a) < 15 and a != obj_name]

                if attrs:
                    for attr in attrs:
                        extracted_objects.add(f"({attr}, {obj_name})")
                else:
                    extracted_objects.add(f"({obj_name})")

        objects_str = ", ".join(sorted(list(extracted_objects))) if extracted_objects else ""
        actions_str = ", ".join(sorted(list(extracted_actions))) if extracted_actions else "none"

        final_output[str(person_counter)] = {
            "person": person_role,
            "object": objects_str,
            "action": actions_str
        }
        person_counter += 1

    return final_output


def extract_attribute_people(args):
    path = args.caption_path

    with open(path, "r") as f:
        generated_caps = json.load(f)

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract the ranking from given sentences."
        },
    ]
    content = """Given an image with a caption that is generated by a vision language model. 
        Please act as a linguistic master and extract the total number and colors of all objects as mentioned in the captions.
        Your answer should be a dict of this format: {"total_num_of_people": "(NUM, PERSON)", "clothes": {"ORDER": "person": "PERSON", "object": "(ATTRIBUTE, OBJECT)", "action": "ACTION"}}. OBJECT can be clothes or accessories (e.g., bags, socks).

        For clarity, consider these examples:

        ### Example 1:
        - Caption: This is an image of three people walking on a beach with a foggy backdrop.\n\nFrom left to right:\n\n1. The first person is wearing a dark green jacket with a hood over their head, blue jeans, and black shoes.\n\n2. The second person has on a bright blue jacket with a hood, burgundy shorts over black leggings, and brown shoes with white soles.\n\n3. The third individual is wearing a black jacket with a hood, blue jeans, and dark shoes with a black backpack.\n\nAll of them are facing away from the camera, walking towards the horizon of the beach where grassy areas can be seen, and there are patches of water, wet sand, and scattered seaweed on the beach.
        - Result: {"total_num_of_objects": "(3, people)", "clothes": {"1": {"person": "person", "object": "(green, jacket), (blue, jeans), (black, shoes)", "action": "walking"}, "2": {"person": "person", "object": "(blue, jacket), (black, leggings), (brown, shoes)", "action": "walking"}, "3": {"person": "person", "object": "(black, jacket), (blue, jeans), (dark, shoes), (black, backpace)", "action": "walking"}}}

        With these examples in mind, please help me extract the relations based on the information in the caption. You should only return a JSON file without any explanations.
        Here is the caption:
        [CAPTION]
    """

    # outpath = args.output_file_path
    out_list = []
    for sample in tqdm.tqdm(generated_caps[:args.sample_num]):
        image_id = sample["image_id"]
        conversation = sample["conversations"]
        if "scene_graph" in sample:
            attributes = format_people_attribute(sample["scene_graph"]["objects"])
        elif "sg" in sample:
            attributes = format_people_attribute(sample["sg"])
        else:
            attributes = format_people_attribute(sample)
        for turn in conversation:
            cap_to_gpt = turn['response']

            input = content.replace("[CAPTION]", cap_to_gpt)
            prompt = messages + [{"role": "user", "content": input}]
            llm_output = llm(prompt, args.model)
            current_output = {
                "image_id": image_id,
                "response": llm_output,
                "generated_caption": cap_to_gpt,
                "gt_attributes": attributes,
                "conversations": conversation
            }
            # with open(outpath, "a") as f:
            #     f.write(json.dumps(current_output) + "\n")
            #
            # print(llm_output)
            out_list.append(current_output)
    return out_list


def match_attribute_people(args, generated_cap_info):
    prompt_template = """Task: Match the correct (attribute, object) with the same meaning from a ground truth dictionary and a generated dictionary.

    Inputs:
    1. "gt_att_obj": A dictionary of ground truth (attribute, object) pairs. Each key is a number starting from 1 and increment each time by 1. Each value is the corresponding (attribute, object) paird related to a person. 
    Sometimes one object can be, for example "(black, bag), (white, bag), (striped, bag)", it means either "black" or "white" or "striped" is correct for an attribute related with the "bag" and should be matched. 
    2. "generated_att_obj": A dictionary with order being the key and the (attribute, object) pairs related to a person being the value. The order is the order of the object in the generated caption.

    Instructions:
    1. Matching Criteria:
    - For each (attribute, object) in "generated_att_obj", find the (attribute, object) in the "gt_att_obj" that have the same meaning and add it to the "matched_att_obj" dictionary. Remeber these matched (attribute, object) pairs should be related to the same person.
    - By the same meaning, we mean the words can be synonyms, can be plural/singular forms of each other and can also have different length of words to express the same meaning of attributes or objects, etc. 
    - Notice that the final "matched_att_obj" must follow the order of values in "generated_att_obj". 
    - If you find that the "generated_att_obj" can be matched with the "gt_att_obj" but the attribute or object in "generated_att_obj" is a broader concept of the attribute or object in "gt_att_obj", for example, one object in "generated_att_obj" is "person", but the "gt_att_obj" don't have "person" but specifically have "man", which is a subcategory of "person", add it to the "broader_concept" dictionary instead of the "matched_att_obj".
    2. Output:
    - A "broader_concept" dictionary: {"ORDER": {"person": {"PERSON1": "PERSON2"}, "object": {"(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)", "(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)", ...}} only if a PERSON1 from "generated_att_obj" matched a PERONS2 from "gt_att_obj" and (ATTRIBUTE1, OBJECT1) from "generated_att_obj" denotes a broader category of an (ATTRIBUTE2, OBJECT2) in "gt_att_obj". Notify that Keys must be the (ATTRIBUTE1, OBJECT1) from "generated_att_obj", Values must be (ATTRIBUTE2, OBJECT2) from "gt_att_obj". If none, it should be an empty dictionary.
    - A "matched_att_obj" dictionary: {"ORDER": {"person": {"PERSON1": "PERSON2"}, "object": {"(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)", "(ATTRIBUTE1, OBJECT1)": "(ATTRIBUTE2, OBJECT2)", ...}} only if a PERSON1 from "generated_att_obj" matched a PERONS2 from "gt_att_obj" and an (ATTRIBUTE1, OBJECT1) from "generated_att_obj" can be mapped to an (ATTRIBUTE2, OBJECT2) in "gt_att_obj" with the matching criteria. Keys must be (ATTRIBUTE1, OBJECT1) from "generated_att_obj", Values must be (ATTRIBUTE2, OBJECT2) from "gt_att_obj". It should not contain any (ATTRIBUTE1, OBJECT1) or (ATTRIBUTE2, OBJECT2) from the "broader_concept" dictionary.
    - One key can contain a list of matched (ATTRIBUTE, OBJECT) pairs.
    - In "broader_concept" and "matched_att_obj", you cannot map two different (ATTRIBUTE1, OBJECT1) from "generated_att_obj" to the same (ATTRIBUTE2, OBJECT2) from "gt_att_obj" twice.
    - REMEMBER both "broader_concept" and "matched_objects" should contain the person information.

    For clarity, consider these examples:

    ### Example 1:
    - gt_att_obj: {"1": {"person": "woman", "object": "(black, blazer), (pink, pants), (brown, shoes), (green, hat)", "action": "standing, hugging"}, "2": {"person": "man", "object": "(red, scarf), (red, jacket), (white, pants), (brown, purse), (black, shoes)", "action": "standing"}}
    - generated_att_obj: {"1": {"person": "man", "object": "(red, jacket), (brown, handbag), (red, scarf)", "action": "holding"}, "2": {"person": "woman", "object": "(black, jacket), (pinkish, pants), (brown, purse), (green, hat)", "action": "being held"}}
    - broader_concept: {"1": {"person": {"man": "man"}, "object": {"(brown, handbag)": "(brown, purse)"}, "2": {"person": {"woman": "woman"}, "object": {"(black, jacket)": "(black, blazer)"}}}
    - matched_objects: {"1": {"person": {"man": "man"}, "object": {"(red, jacket)": "(red, jacket)", "(red, scarf)": "(red, scarf)"}}, "2": {"person": {"woman": "woman"}, "object": {"(pinkish, pants)": "(pink, pants)", "(green, hat)": "(green, hat)"}}}

    With these examples in mind, please help me extract the broader_concept, and matched_objects from the following two inputs. Please note that your answer should only be in a JSON format with the keys only being the broader_concept, and matched_att_obj.  No explanations/note included.
    ```
    - gt_att_obj: [GT_ATT_OBJ]
    - generated_att_obj: [GENERATED_ATT_OBJ]
    ```  
    """

    # with open(args.gt_file_path, "r") as f:
    #     gt_cap_info = json.load(f)
    #
    # with open(args.generated_file_path, "r") as f:
    #     generated_cap_info = [json.loads(l) for l in f.readlines()]

    # if args.random:
    #     cap_info = random.sample(cap_info, args.num_random_samples)

    output_file = {}

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract information from given sentences."
        },
    ]
    out_list = []
    for cap in tqdm.tqdm(generated_cap_info):
        image_id = cap["image_id"]
        generated_obj_atts = cap["response"]["clothes"]

        generated_obj_atts_copy = generated_obj_atts.copy()
        for key, value in generated_obj_atts_copy.items():
            if value["object"] in ['()', '(none, none)', '(none)', '(unknown, clothes)']:
                del generated_obj_atts[key]
        if len(generated_obj_atts) == 0:
            continue

        gt_obj_atts = cap["gt_attributes"]

        content = prompt_template.replace("[GT_ATT_OBJ]", str(gt_obj_atts))
        content = content.replace("[GENERATED_ATT_OBJ]", str(generated_obj_atts))

        prompt = messages + [{"role": "user", "content": content}]
        llm_output_dict = llm(prompt, args.model)

        # print(image_id, llm_output_dict)
        output_file[image_id] = llm_output_dict
        current_output = {
            "image_id": image_id,
            "gt_obj_atts": gt_obj_atts,
            "generated_obj_atts": generated_obj_atts,
            "matched_att_obj": llm_output_dict["matched_att_obj"],
            "broader_concept": llm_output_dict["broader_concept"],
            "conversations": cap["conversations"]
        }
        out_list.append(current_output)
        # with open(args.output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    return out_list


def postprocess_attribute_people(matched_att_obj_file):
    out_list = {}
    for matched_att_obj in matched_att_obj_file:
        # Original list of attributes from matched objects
        gt_obj_atts = matched_att_obj["gt_obj_atts"].values()
        gt_obj_atts = [gt_obj_att["object"] for gt_obj_att in gt_obj_atts]
        # Splitting each string on "),", then flattening the list and stripping spaces
        gt_obj_atts_list = [item.strip() for atts in gt_obj_atts for item in atts.split("),")]
        # Initialize a new list for processed attributes
        new_gt_obj_atts_list = []
        for item in gt_obj_atts_list:
            # Append a ")" to odd indexed items if missing
            if len(item) and item[-1] != ")":
                item += ")"
            new_gt_obj_atts_list.append(item)

        # Initialize the new dictionaries
        new_matched_att_obj = {}
        new_broader_concept = {}
        # Update "new_matched_att_obj" by filtering out the relevant mappings
        for index, mapping in matched_att_obj["matched_att_obj"].items():
            if mapping.get("object") != None:
                matched_obj_atts_dict = mapping.get("object")
                new_mapping = {}
                new_mapping_objects = {}
                for matched_ge_obj_atts, matched_gt_obj_atts in matched_obj_atts_dict.items():
                    if matched_gt_obj_atts in new_gt_obj_atts_list:
                        new_mapping_objects[matched_ge_obj_atts] = matched_gt_obj_atts
                        new_gt_obj_atts_list.remove(matched_gt_obj_atts)

                if mapping.get("person") != None and mapping.get("object") != None:
                    new_mapping["person"] = mapping["person"]
                    new_mapping["object"] = new_mapping_objects
                    new_matched_att_obj[index] = new_mapping

        # Update "new_broader_concept" in a similar way
        for index, mapping in matched_att_obj["broader_concept"].items():
            if mapping.get("object") != None:
                matched_obj_atts_dict = mapping.get("object")
                new_mapping = {}
                new_mapping_objects = {}
                for matched_ge_obj_atts, matched_gt_obj_atts in matched_obj_atts_dict.items():
                    if matched_gt_obj_atts in new_gt_obj_atts_list:
                        new_mapping_objects[matched_ge_obj_atts] = matched_gt_obj_atts
                        new_gt_obj_atts_list.remove(matched_gt_obj_atts)

                if mapping.get("person") != None and mapping.get("object") != None:
                    new_mapping["person"] = mapping["person"]
                    new_mapping["object"] = new_mapping_objects
                    new_broader_concept[index] = new_mapping

        image_id = matched_att_obj["image_id"]
        if image_id not in out_list.keys():
            current_output = {
                "image_id": matched_att_obj["image_id"],
                "gt_obj_atts": matched_att_obj["gt_obj_atts"],
                "generated_obj_atts": matched_att_obj["generated_obj_atts"],
                "matched_att_obj": new_matched_att_obj,
                "broader_concept": new_broader_concept,
                "conversations": matched_att_obj["conversations"]
            }
            out_list[matched_att_obj["image_id"]] = current_output
        else:
            item_len = len(out_list[image_id]["generated_obj_atts"].keys())
            for key, value in matched_att_obj["generated_obj_atts"].items():
                out_list[image_id]["generated_obj_atts"][f'{item_len+int(key)}'] = value

            item_len = len(out_list[image_id]["matched_att_obj"].keys())
            for key, value in matched_att_obj["matched_att_obj"].items():
                out_list[image_id]["matched_att_obj"][f'{item_len+int(key)}'] = value

            item_len = len(out_list[image_id]["broader_concept"].keys())
            for key, value in matched_att_obj["broader_concept"].items():
                out_list[image_id]["broader_concept"][f'{item_len+int(key)}'] = value

        # with open(output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    list_of_dicts = [inner_dict for inner_dict in out_list.values()]
    return list_of_dicts


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="objects extracting")
    parser.add_argument("-ip", "--caption_path",  default='output/caption/Qwen2.5-VL-3B-Instruct_svg.json', type=str)
    parser.add_argument("-op", "--output_file_path", default="output/caption/valor/Qwen2.5-VL-3B-Instruct_svg_valor_people.json", type=str)
    parser.add_argument("--model", type=str, default='gpt-5')
    parser.add_argument("--sample_num", type=int, default=3)
    args = parser.parse_args()

    people_attribute_list = extract_attribute_people(args)
    match_attribute_list = match_attribute_people(args, people_attribute_list)
    match_attribute_list = postprocess_attribute_people(match_attribute_list)

    evaluator = CHAIR(match_attribute_list)
    cap_dict = evaluator.compute_chair()

    print_metrics(cap_dict)
    save_evaluation_results(args, cap_dict)