import json
import tqdm
import argparse
from gpt_model import llm
from copy import deepcopy
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from graders.valor.scorer.valor_eval_relation_comparative import CHAIR, print_metrics, save_evaluation_results

lemmatizer = WordNetLemmatizer()


def calculate_object_size(obj) -> float:
    if 'w' in obj:
        w = obj.get('w', 0.0)
        h = obj.get('h', 0.0)
    else:
        w = obj["bbox"][2]
        h = obj["bbox"][3]

    # Ensure w and h are numeric before multiplication
    if not isinstance(w, (int, float)) or not isinstance(h, (int, float)):
        return 0.0

    return w * h


def get_ranked_object_names(all_objects):
    for obj in all_objects:
        obj['size'] = calculate_object_size(obj)

    sorted_objects = sorted(
        all_objects,
        key=lambda obj: obj.get('size', 0),
        reverse=True
    )

    ranked_names = {}
    for i, obj in enumerate(sorted_objects):
        if 'names' in obj:
            object_name = obj.get('names', ['none'])[0]
        else:
            object_name = obj.get('object', ['none'])
        object_name = lemmatizer.lemmatize(object_name, pos=wordnet.NOUN)
        if  object_name not in ranked_names.values():
            ranked_names[f'{i + 1}'] = object_name

    return ranked_names


def extract_relation_comparative(args):
    path = args.input_file_path

    with open(path, 'r') as f:
        generated_caps = json.load(f)

    messages = [
        {
            "role": "system",
            "content": "You are a language assistant that helps to extract the ranking from given sentences."
        },
    ]
    content = """Given an image with a caption that is generated by a vision language model. 
        Please act as a linguistic master and extract the rank of all the objects from large to small as mentioned in the captions.
        Your answer should be a dict of values which the keys represent the ranks starting from 1 and values are the No.1 largest object to smallest.
        If the caption does not mention the order of the object, you can by default view the order of objects appearance as from largest to smallest.
        If there are no objects mentioned in the caption, you can return an empty dict.
        For clarity, consider these examples:

        ### Example 1:
        - Caption: From largest to smallest, the objects in the image are a large brown teddy bear, a green trash can, and two black trash bags. The teddy bear is the largest object, followed by the green trash can, and then the two black trash bags
        - rank: {{"1": "teddy bear", "2": "green trash can", "3": "black trash bags"}}

        ### Example 2:
        - Caption: In the image, there are two young children, a boy and a girl, standing next to each other in a kitchen. The boy is wearing a chef's hat, while the girl is holding a piece of broccoli. They appear to be preparing food together, possibly for a meal or snack.There are several objects in the kitchen, including a bowl, a knife, a book, a cup, and a bottle. These items suggest that the kitchen is well-equipped and suitable for cooking and preparing meals
        - rank: {{"1": "boy", "2": "girl", "3": "broccoli", "4": "bowl", "5": "knife", "6": "book", "7": "cup", "8": "bottle"}}

        ### Example 3:
        - Caption: 1. Tennis court (large) 2. Man holding a tennis racket (medium) 3. Woman wearing a red hat (medium) 4. Woman wearing a blue dress (medium) 5. Chairs (small) 6. Tennis ball (small)
        - rank: {{"1": "Tennis court", "2": "Man holding a tennis racket", "3": "Woman wearing a red hat", "4": "Woman wearing a blue dress", "5": "Chairs", "6": "Tennis ball"}}

        ### Example 4:
        - Caption: box
        -rank : {{"1": box}}

        With these examples in mind, please help me extract the relations based on the information in the caption.
        Here is the caption:
        {}"""

    # outpath = args.output_file_path
    out_list = []
    for sample in tqdm.tqdm(generated_caps[:args.sample_num]):
        image_id = sample["image_id"]
        conversation = sample["conversations"]

        if "scene_graph" in sample:
            objects = get_ranked_object_names(sample["regions"])
        elif "sg" in sample:
            objects = get_ranked_object_names(sample["sg"]["objects"].values())
        else:
            objects = get_ranked_object_names(sample["objects"])

        cap_to_gpt = ''
        for turn in conversation:
            cap_to_gpt += f" {turn['response']}"

        input = content.format(cap_to_gpt)
        prompt = messages + [{"role": "user", "content": input}]
        llm_output = llm(prompt, args.model)
        current_output = {
            "image_id": image_id,
            "generated_words": llm_output,
            # "generated_caption": cap_to_gpt,
            "gt_words": objects,
            "conversations": conversation
        }
        out_list.append(current_output)
        # with open(outpath, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
        #
        # print(llm_output)
    return out_list


def match_relation_comparative(cap_info):
    prompt_template = """
        Task: Match the correct objects with the same meaning from a ground truth dictionary and a generated dictionary.

        Inputs:
        1. "gt_objects": A dictionary of ground truth objects. Each key is a number starting rank No. 1 and increment each time by 1. Each value is the correpsonding object with the rank.
        Sometimes one object can be, for example "ground / court, it means either ground or court is correct and should be matched. 
        2. "generated_objects": A dictionary with rank being the key and the object being the value. The rank is the rank of the object in the generated caption.

        Instructions:
        1. Matching Criteria:
        - For each object in "generated_objects", find the object in the "gt_objects" that have the same meaning and add it to the "matched_objects" dictionary.
        - By the same meaning, we mean the words can be synonyms, can be plural/singular forms of each other and can also have different length of words to express the same meaning of objects, etc. 
        - Notice that the final macthed_objects must follow the order of values in "generated_objects". 
        - If you find that the "generated_objects" can be matched with the "gt_objects" but the object in "generated_objects" is a broader concept of the objects in "gt_objects", for example, one object in "generated_objects" is "person", but the "gt_objects" don't have "person" but specifically have "man", which is a subcategory of "person", add it to the "broader_concept" dictionary instead of the "matched_objects".    
        2. Output:
        - A "broader_concept" dictionary: only if an object from "generated_objects" denotes a broader category of a concept in "gt_objects" Notify that Key must be the item from "generated_objects", Value must be item from "gt_objects". If none, it should be an empty dictionary.
        - A "matched_objects" dictionary: only if an object from "generated_objects" can be mapped to an object in "gt_objects" with the matching criteria. Key must be word from "generated_objects", Value must be word from "gt_objects". It should not contain any words from the "broader_concept" dictionary.

        For clarity, consider these examples:

        ### Example 1:
        - gt_objects:{"1": "stove", "2": "table", "3": "cabinet", "4": "bottle / wine", "5": "mug / cup / coffee", "6": "glass", "7": "spoon"}
        - generated_objects: {'1': 'bottle', '2': 'mug', '3': 'spoon', '4': 'stove'}
        - broader_concept: {}
        - matched_objects: {'bottle': 'bottle / wine', 'mug': 'mug / cup / coffee', 'spoon': 'spoon', 'stove': 'stove'}

        ### Example 2:
        - gt_objects: {"1": "grass ground", "2": "tennis court", "3": "net background", "4": "man", "5": "woman", "6": "chair", "7": "racket"}
        - generated_objects: {"1": "man", "2": "tennis racket", "3": "chairs", "4": "person", "5": "ball"}
        - broader_concept: {"person": "man"}
        - matched_objects: {"man": "man", "tennis racket": "racket", "chairs": "chair"}
        Notice the broader_concept here can either be {"person": "man"} or {"person": "woman"} as both man and woman is a sub category of person. 

        With these examples in mind, please help me extract the broader_concept, and matched_objects from the following two inputs.
        ```
        - gt_objects: [GT_RELATIONS]
        - generated_objects: [GENERATED_RELATIONS]
        ```
        Please note that your answer should only be in a JSON format with the keys only being the broader_concept, and matched_objects.
        No explanations/note included.
    """

    # with open(args.input_file_path, "r") as f:
    #     cap_info = [json.loads(l) for l in f.readlines()]

    output_file = {}
    out_list = []
    for cap in tqdm.tqdm(cap_info):
        image_id = cap["image_id"]
        gt_objects = cap["gt_words"]
        generated_objects = cap["generated_words"]
        # generated_caption = cap["generated_caption"]

        content = prompt_template.replace("[GT_RELATIONS]", str(gt_objects))
        content = content.replace("[GENERATED_RELATIONS]", str(generated_objects))

        prompt = [{"role": "user", "content": content}]

        if generated_objects == "":
            current_output = {
                "image_id": image_id,
                "gt_words": gt_objects,
                "generated_words": generated_objects,
                "broader_concept": {},
                "matched_objects": {},
                # "generated_caption": generated_caption,
                "conversations": cap["conversations"]
            }
        else:
            llm_output_dict = llm(prompt, args.model)

            output_file[image_id] = llm_output_dict
            current_output = {
                "image_id": image_id,
                "gt_words": gt_objects,
                "generated_words": generated_objects,
                "broader_concept": llm_output_dict["broader_concept"],
                "matched_objects": llm_output_dict["matched_objects"],
                # "generated_caption": generated_caption,
                "conversations": cap["conversations"]
            }

            # print("broader_concept", llm_output_dict["broader_concept"])
            # print("matched_objects", llm_output_dict["matched_objects"])
        out_list.append(current_output)
        # with open(args.output_file_path, "a") as f:
        #     f.write(json.dumps(current_output) + "\n")
    return out_list


def longest_monotonic_subsequence(arr):
    """
    Find the longest monotonic increasing subsequence in an array.

    :param arr: List of integers (ranks)
    :return: The longest monotonic increasing subsequence.
    """
    if not arr:
        return []

    # Initialize the dp array where dp[i] will store the longest increasing subsequence ending with arr[i]
    dp = [[num] for num in arr]

    # Fill the dp array
    for i in range(1, len(arr)):
        for j in range(i):
            if arr[i] > arr[j] and len(dp[i]) < len(dp[j]) + 1:
                dp[i] = dp[j] + [arr[i]]

    # Find the longest subsequence
    longest_subsequence = max(dp, key=len)

    return longest_subsequence


def popstprocess_relation(cap_info):
    for item in cap_info:
        if item["generated_words"] == "":
            item["matched_objects_filtered"] = []
            item["num_broader_concept_filtered"] = 0
            continue

        gt_to_rank = {}
        for k, v in item["gt_words"].items():
            gt_to_rank[v] = k

        broader_concept = item["broader_concept"]
        broader_concept_copy = deepcopy(broader_concept)

        for k, o in broader_concept_copy.items():
            if o in gt_to_rank.keys():
                pass
            else:
                for oo in o.split('/'):
                    oo = oo.strip()
                    if oo in gt_to_rank.keys():
                        broader_concept.pop(k, o)
                        broader_concept[k] = oo
        broader_concept_ranks = [int(gt_to_rank[o]) for o in broader_concept.values() if o in gt_to_rank]
        item["broader_concept"] = broader_concept
        joint_objects = {**item["broader_concept"], **item["matched_objects"]}

        mapped_objects = []
        for k, v in item['generated_words'].items():
            if v in joint_objects.keys():
                mapped_objects.append(joint_objects[v])

        ranks = [int(gt_to_rank[o]) for o in mapped_objects]

        ranks = longest_monotonic_subsequence(ranks)

        item["matched_objects_filtered"] = [item['gt_words'][str(i)] for i in ranks]

        diff = len(set(broader_concept_ranks) - set(ranks))
        item["num_broader_concept_filtered"] = diff

    # with open(args.output_file_path, "w") as f:
    #     for item in cap_info:
    #         f.write(json.dumps(item) + "\n")
    return cap_info


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="objects matching")
    parser.add_argument("-ip", "--input_file_path", default='output/caption/Qwen2.5-VL-3B-Instruct_svg.json', type=str)
    parser.add_argument("-op", "--output_file_path", default="output/caption/valor/Qwen2.5-VL-3B-Instruct_svg_valor_com.json", type=str)
    parser.add_argument("--model", type=str, default='gpt-5')
    parser.add_argument("--sample_num", type=int, default=3)
    args = parser.parse_args()

    caption_list = extract_relation_comparative(args)
    relation_list = match_relation_comparative(caption_list)
    popstprocess_relation_list = popstprocess_relation(relation_list)

    evaluator = CHAIR(popstprocess_relation_list)
    cap_dict = evaluator.compute_chair()

    print_metrics(cap_dict)
    save_evaluation_results(args, cap_dict)
