from utils.llm import LLMChat
import os
import argparse
import json
import tqdm

CLAIM_PROMPT = '''Given a segment of text generated by a large visual language model, the assertion is a statement that claims whether something conflicts with visual information and can be verified by humans. Your task is to first divide the text into segments, then accurately identify and extract every asserted claim within each segment. Then, resolve any coreference (pronouns or other referring expressions) in the claim for clarity. 
Each claim should be concise (less than 15 words), self-contained, which contain information related to physical object(s) and corresponding attributes or relationships. Keep the adjectives used to describe the physical traits of the identified objects only (e.g. color, size).

Your response MUST be a list of dictionaries. Each dictionary contains two keys, "segment" and "claims." The key "segment" corresponds to each segment of the given text (each segment should match the original text's segments and be arranged in the original order). Then, the value corresponding to the key "claims" is a list of assertions, extracted based on this segment. Each dictionary within this list should contain the key "claim," corresponding to the extracted claim (with all references resolved).
You MUST only respond in the format as described below. DO NOT RESPOND WITH ANYTHING ELSE. ADDING ANY OTHER EXTRA NOTES THAT VIOLATE THE RESPONSE FORMAT IS BANNED. START YOUR RESPONSE WITH '['.
WHEN THERE ARE DOUBLE QUOTATION MARKS " IN THE GENERATED SEGMENT AND CLAIM, YOU NEED TO ADD AN ESCAPE CHARACTER " BEFORE THEM!!!
[response format]: 
[
{{
    "segment":"Ensure that the segment match the original text's segments corresponds to each segment of the given text(each segment should match the original text's segments and be arranged in the original order)",
    "claims":[{{
    "claim": "Ensure that the claim is fewer than 15 words and conveys a complete idea. Resolve any coreference (pronouns or other referring expressions) in the claim for clarity. Keep the adjectives used to describe the physical traits of the identified physical objects only (e.g. color, size, shape, material)",
}},
...]
}},
...
]

Here are two examples:
[text]: There are a man and a woman. They stand on street.
[response]: [{{"segment": "There are a man and a woman. They stand on street.","claims": [{{"claim": "A man stands on street.", "claim": "A woman stands on street."}}]}}]

[text]: The book with the cover featuring Dylan Thomas, \"Quite Early One Morning,\" was published in 1999, and was written by Dylan Thomas himself.
[response]: [{{"segment": "The book with the cover featuring Dylan Thomas, \"Quite Early One Morning,\" was published in 1999, and was written by Dylan Thomas himself.","claims": [{{"claim": "The book has cover."}}]}}]

[text]:{text}
[response]:'''

SG_PROMPT = '''Given a segment of text generated by a large visual language model, the assertion is a statement that claims whether something conflicts with visual information and can be verified by humans. Your task is to first divide the text into segments, then accurately identify and extract every asserted claim within each segment. Then, resolve any coreference (pronouns or other referring expressions) in the claim for clarity. Each claim should be concise (less than 15 words), self-contained.
Your response MUST be a list of dictionaries. Each dictionary contains two keys, "segment" and "claims." The key "segment" corresponds to each segment of the given text (each segment should match the original text's segments and be arranged in the original order). Then, the value corresponding to the key "claims" is a list of assertions, extracted based on this segment. Each dictionary within this list should contain the key "claim," corresponding to the extracted claim (with all references resolved).
You MUST only respond in the format as described below. DO NOT RESPOND WITH ANYTHING ELSE. ADDING ANY OTHER EXTRA NOTES THAT VIOLATE THE RESPONSE FORMAT IS BANNED. START YOUR RESPONSE WITH '['.
WHEN THERE ARE DOUBLE QUOTATION MARKS " IN THE GENERATED SEGMENT AND CLAIM, YOU NEED TO ADD AN ESCAPE CHARACTER " BEFORE THEM!!!
[response format]: 
[
{{
    "segment":"Ensure that the segment match the original text's segments corresponds to each segment of the given text(each segment should match the original text's segments and be arranged in the original order)"
    "claims":[{{
    "claim": "Ensure that the claim is fewer than 15 words and conveys a complete idea. Resolve any coreference (pronouns or other referring expressions) in the claim for clarity",
}},
...]
}},
...
]

Here are two examples:
[text]: This drink is Fresca. It is a lemon-lime flavored soft drink, commonly available in the United States.
[response]: [{{"segment": "This drink is Fresca.","claims": [{{"claim": "This drink is Fresca"}}]}}, {{"segment": "It is a lemon-lime flavored soft drink, commonly available in the United States.","claims": [{{"claim": "Fresca is a lemon-lime flavored soft drink"}}, {{"claim": "Fresca is commonly available in the United States"}}]}}]

[text]: The book with the cover featuring Dylan Thomas, \"Quite Early One Morning,\" was published in 1999, and was written by Dylan Thomas himself.
[response]: [{{"segment": "The book with the cover featuring Dylan Thomas, \"Quite Early One Morning,\" was published in 1999, and was written by Dylan Thomas himself.","claims": [{{"claim": "\"Quite Early One Morning\" was published in 1999"}}, {{"claim": "The book's cover features Dylan Thomas"}}, {{"claim": "The book was written by Dylan Thomas"}}],}}]

[text]:{text}
[response]:'''

CAPTION_PROMPT = '''Given a script where a single speaker describes a given image, your task is to generate concise and diverse captions that capture the physical elements of the description.  

Instructions:  
1. Read the description carefully.  
2. Identify the key objects, attributes, and relationships mentioned.  
3. Generate captions that describe only the physical aspects of the scene.  

Each caption must follow these rules:  
- Be fewer than 15 words.  
- Be self-contained and understandable without additional context.  
- Include only physical details (objects, colors, sizes, shapes, spatial relations, materials).  
- Exclude emotions, opinions, or interpretations.  
- Write in natural, human-like phrasing (as if for photo captions or alt text).  

Your response MUST be a dictionary in valid JSON format. 
Each entry must have a unique key in the form "captionN" (e.g., "caption1", "caption2", etc.), 
and the value must be the generated caption text. 
Do not include any extra text, explanation, or formatting outside of the JSON object.

There are no restrictions on the number of captions you may generate.

[Response format]:
{
  "caption1": "Caption text 1",
  "caption2": "Caption text 2",
  "caption3": "Caption text 3"
}

[Example]
[text]:
I see a young boy holding a bright red balloon. He’s standing in a park with tall green trees in the background. The sun is shining overhead.

[response]:
{
  "caption1": "A boy holds a bright red balloon",
  "caption2": "Tall green trees stand in the background",
  "caption3": "The sun shines above the park",
  "caption4": "A child stands in the park",
  "caption5": "A red balloon contrasts with the green trees"
}

[text]:
'''


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--infile", type=str)
    parser.add_argument('--outfile', type=str)
    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.outfile), exist_ok=True)
    samples = json.load(open(args.infile, "r"))

    agent = LLMChat("gpt-4o")

    print("starting conversation with model...")
    for sample in tqdm.tqdm(samples):
        claims = []
        for conversation in sample["conversations"]:
            claims.append(conversation["response"])
        
        claims = " ".join(claims)
        input_to_gpt = [
            {"role": "system", "content": f"You are a brilliant claim generator. {CLAIM_PROMPT}"},
            {"role": "user", "content": claims}
        ]
        output = agent.chat(input_to_gpt, None)
        print(output)
        import sys; sys.exit()
    
    with open(args.outfile, "w") as f:
        json.dump(samples, f, indent=4)
